### ISSUE TITLE
--solver_lm throwing error

### ISSUE THREAD

**Issue by thisisanameforsure** [billxbf/ReWOO#1]
You have a typo for solver_lm, its written as sovler_lm 

usage: run.py [-h] [--method {direct,cot,react,rewoo}] [--exemplar EXEMPLAR]
              [--toolset TOOLSET [TOOLSET ...]] [--base_lm BASE_LM] [--planner_lm PLANNER_LM]
              [--sovler_lm SOVLER_LM] [--print_trajectory] [--key_path KEY_PATH]
run.py: error: unrecognized arguments: --solver_lm gpt-3.5-turbo

**Comment by billxbf** [comment]
Thank you! The typo is fixed.
