### ISSUE TITLE
why do we need the worker phase?

### ISSUE THREAD

**Issue by hyusetiawan** [billxbf/ReWOO#12]
using gpt-4 i am able to generate plans that are interdependent as a json that i can immediately execute by looping through them, at this point, we don't need the worker phase right? I can just pass the result of the execution straight to the solver?

**Comment by billxbf** [comment]
Sure, the worker is just a stage for executing those plans. 
And since the plans are interdependent, you can parallelize the execution in most cases.
See below for a 8-plan example
https://youtu.be/diJ4IDaT4Z4?t=116

**Comment by billxbf** [comment]
Closing this thread as solved.
