### ISSUE TITLE
langchain version 

### ISSUE THREAD

**Issue by Fazziekey** [billxbf/ReWOO#6]
what is the right langchain version you use, I install 0.0.18 and  get wrong
![image](https://github.com/billxbf/ReWOO/assets/55798671/0ee54b63-9469-43f0-b2df-8677737b8657)

**Comment by billxbf** [comment]
Here's my package info.
![image](https://github.com/billxbf/ReWOO/assets/65674752/edba73d5-4e0e-4069-a1be-f8af39c2efd4)

I checked StackOverflow 
https://stackoverflow.com/questions/76021476/modulenotfounderror-no-module-named-langchain-agents 
It seems like an issue with your Python version. Try 3.9
